name: Code Review

on:
  push:
    branches: [ main, review ]
  pull_request:
    branches: [ main, review ]

jobs:
  lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run GitHub Super-Linter
      uses: github/super-linter@v6
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
